export interface Password {
  category: string;
  answer: string;
}

// Temat to uczciwa podpowiedź: hasło naprawdę do niego pasuje, bez gier słownych na siłę.
// Hasła mają co najmniej 3 słowa; zasady pilnuje tests/passwords.test.ts.
const BANK: Record<string, string[]> = {
  "Przysłowie": [
    "Nie chwal dnia przed zachodem słońca",
    "Kto rano wstaje, temu Pan Bóg daje",
    "Nie ma tego złego, co by na dobre nie wyszło",
    "Kto pod kim dołki kopie, ten sam w nie wpada",
    "Co ma wisieć, nie utonie",
    "Mądry Polak po szkodzie",
    "Prawdziwych przyjaciół poznaje się w biedzie",
    "Bez pracy nie ma kołaczy",
    "Kuj żelazo, póki gorące",
    "Wszędzie dobrze, ale w domu najlepiej",
    "Fortuna kołem się toczy",
    "Cicha woda brzegi rwie",
    "Kłamstwo ma krótkie nogi",
    "Nie od razu Kraków zbudowano",
    "Jak sobie pościelesz, tak się wyśpisz",
    "Nie wszystko złoto, co się świeci",
    "Tonący brzytwy się chwyta",
    "Mowa jest srebrem, a milczenie złotem",
    "Od przybytku głowa nie boli",
    "Czego Jaś się nie nauczy, tego Jan nie będzie umiał",
    "Nie mów hop, póki nie przeskoczysz",
    "Gość w dom, Bóg w dom",
    "Uderz w stół, a nożyce się odezwą",
    "Lepiej późno niż wcale",
    "Kto nie ryzykuje, ten nie pije szampana",
    "Wyjątek potwierdza regułę",
    "Potrzeba matką wynalazków",
    "Co się odwlecze, to nie uciecze",
    "Kto mieczem wojuje, od miecza ginie",
    "Ile krajów, tyle obyczajów",
    "Grosz do grosza, a będzie kokosza",
    "Czym skorupka za młodu nasiąknie, tym na starość trąci",
    "Wyszło szydło z worka",
    "Kto z kim przestaje, takim się staje",
  ],
  "Przysłowie o zwierzętach": [
    "Darowanemu koniowi w zęby się nie zagląda",
    "Lepszy wróbel w garści niż gołąb na dachu",
    "Jedna jaskółka wiosny nie czyni",
    "Nosił wilk razy kilka, ponieśli i wilka",
    "Gdy kota nie ma, myszy harcują",
    "Pierwsze koty za płoty",
    "Dzieci i ryby głosu nie mają",
    "Baba z wozu, koniom lżej",
    "Na bezrybiu i rak ryba",
    "Wilk syty i owca cała",
    "Łaska pańska na pstrym koniu jeździ",
    "Nie wywołuj wilka z lasu",
    "Psy szczekają, karawana jedzie dalej",
  ],
  "Przysłowie o jedzeniu": [
    "Apetyt rośnie w miarę jedzenia",
    "Przez żołądek do serca",
    "Gdzie kucharek sześć, tam nie ma co jeść",
    "Jakie sobie piwo nawarzysz, takie wypijesz",
    "Kto nie pracuje, ten nie je",
    "Głodnemu chleb na myśli",
    "Musztarda po obiedzie",
    "Nie dla psa kiełbasa",
    "Lepszy rydz niż nic",
    "Co za dużo, to niezdrowo",
  ],
  "Pogoda": [
    "W marcu jak w garncu",
    "Kwiecień plecień, bo przeplata trochę zimy, trochę lata",
    "Idzie luty, podkuj buty",
    "Barbara po lodzie, Boże Narodzenie po wodzie",
    "Po burzy zawsze wychodzi słońce",
    "Nie ma złej pogody, są tylko złe ubrania",
    "Zima zaskoczyła drogowców",
    "Leje jak z cebra",
    "Zimno jak w psiarni",
    "Burza z piorunami i gradem",
    "Upał nie do wytrzymania",
    "Tęcza po letniej burzy",
  ],
  "Powiedzenie": [
    "Robić z igły widły",
    "Szukać igły w stogu siana",
    "Wylać dziecko z kąpielą",
    "Nie mój cyrk, nie moje małpy",
    "Dmuchać na zimne",
    "Nabrać wody w usta",
    "Palić za sobą mosty",
    "Rzucać słowa na wiatr",
    "Mieć głowę w chmurach",
    "Kręcić jak pies ogonem",
    "Wpuścić kogoś w maliny",
    "Wyjść jak Zabłocki na mydle",
    "Włożyć kij w mrowisko",
    "Spaść jak grom z jasnego nieba",
    "Być w siódmym niebie",
    "Wiercić komuś dziurę w brzuchu",
    "Obiecywać gruszki na wierzbie",
    "Mieć muchy w nosie",
    "Zakopać topór wojenny",
    "Zjeść z kimś beczkę soli",
    "Mieć węża w kieszeni",
    "Kupić kota w worku",
    "Dolewać oliwy do ognia",
    "Grać pierwsze skrzypce",
    "Postawić kropkę nad i",
    "Wyciągać kasztany z ognia cudzymi rękami",
    "Chować głowę w piasek",
    "Zamiatać sprawę pod dywan",
    "Między młotem a kowadłem",
    "Mieć nóż na gardle",
  ],
  "Porównanie": [
    "Czerwony jak burak",
    "Blady jak ściana",
    "Jak grochem o ścianę",
    "Jak dwie krople wody",
    "Pasuje jak pięść do nosa",
    "Cicho jak makiem zasiał",
    "Pijany jak bela",
    "Chodzić jak w zegarku",
    "Iść jak po maśle",
    "Siedzieć jak na szpilkach",
    "Przepaść jak kamień w wodę",
    "Zniknąć jak kamfora",
    "Śmiać się jak głupi do sera",
    "Pasuje jak ulał",
  ],
  "Porównanie ze zwierzętami": [
    "Głodny jak wilk",
    "Uparty jak osioł",
    "Chytry jak lis",
    "Dumny jak paw",
    "Spać jak suseł",
    "Płakać jak bóbr",
    "Zdrowy jak ryba",
    "Biedny jak mysz kościelna",
    "Pracowity jak mrówka",
    "Jak słoń w składzie porcelany",
    "Żyć jak pies z kotem",
    "Czuć się jak ryba w wodzie",
    "Wlec się jak mucha w smole",
    "Mieć pamięć złotej rybki",
  ],
  "Powiedzenie z częścią ciała": [
    "Mieć serce na dłoni",
    "Trzymać język za zębami",
    "Mieć głowę na karku",
    "Stanąć na głowie",
    "Mieć oczy dookoła głowy",
    "Ręka rękę myje",
    "Mieć lepkie ręce",
    "Wziąć nogi za pas",
    "Włos się jeży na głowie",
    "Wodzić kogoś za nos",
    "Mieć coś na końcu języka",
    "Mieć złote ręce",
    "Przymykać na coś oko",
    "Słoń mu na ucho nadepnął",
    "Leżeć do góry brzuchem",
    "Grać komuś na nosie",
    "Owinąć sobie kogoś wokół palca",
    "Wyssać coś z palca",
  ],
  "Cytat": [
    "Być albo nie być",
    "Litwo, ojczyzno moja",
    "Niech Moc będzie z tobą",
    "Houston, mamy problem",
    "Myślę, więc jestem",
    "Wiem, że nic nie wiem",
    "Kości zostały rzucone",
    "Przybyłem, zobaczyłem, zwyciężyłem",
    "Polacy, nic się nie stało",
    "Jestem za, a nawet przeciw",
    "Nie chcem, ale muszem",
    "A jednak się kręci",
    "Chleba i igrzysk",
    "Jeszcze Polska nie zginęła",
    "Kto ty jesteś? Polak mały",
  ],
  "Film": [
    "Tylko mnie kochaj",
    "Piraci z Karaibów",
    "Powrót do przyszłości",
    "Lot nad kukułczym gniazdem",
    "Przeminęło z wiatrem",
    "Kiedy Harry poznał Sally",
    "To właśnie miłość",
    "Kochanie, zmniejszyłem dzieciaki",
    "Harry Potter i Kamień Filozoficzny",
    "Szybcy i wściekli",
    "Jak rozpętałem drugą wojnę światową",
    "Nie lubię poniedziałku",
    "Nie ma mocnych",
    "Kochaj albo rzuć",
    "Chłopaki nie płaczą",
    "Listy do M.",
    "Gdzie jest Nemo",
    "Skazani na Shawshank",
    "Indiana Jones i ostatnia krucjata",
    "Jak wytresować smoka",
    "Kung Fu Panda",
    "Diabeł ubiera się u Prady",
    "Dziennik Bridget Jones",
    "Dwunastu gniewnych ludzi",
    "Pół żartem, pół serio",
  ],
  "Serial": [
    "Czterej pancerni i pies",
    "Świat według Kiepskich",
    "M jak miłość",
    "Stawiam na Tolka Banana",
    "Kariera Nikodema Dyzmy",
    "Stawka większa niż życie",
    "Dom nad rozlewiskiem",
    "Gra o tron",
    "Dom z papieru",
    "Na dobre i na złe",
    "Daleko od szosy",
    "Przygody pana Michała",
    "Gotowe na wszystko",
    "Seks w wielkim mieście",
  ],
  "Program telewizyjny": [
    "Jaka to melodia",
    "Randka w ciemno",
    "Taniec z gwiazdami",
    "Rolnik szuka żony",
    "Pytanie na śniadanie",
    "Sprawa dla reportera",
    "Jeden z dziesięciu",
    "Szansa na sukces",
    "Idź na całość",
  ],
  "Książka": [
    "W pustyni i w puszczy",
    "Ogniem i mieczem",
    "Kamienie na szaniec",
    "Zbrodnia i kara",
    "Stary człowiek i morze",
    "Chłopcy z Placu Broni",
    "Akademia pana Kleksa",
    "Dzieci z Bullerbyn",
    "Ania z Zielonego Wzgórza",
    "Przygody Tomka Sawyera",
    "Alicja w Krainie Czarów",
    "Hobbit, czyli tam i z powrotem",
    "Harry Potter i Komnata Tajemnic",
    "Pan Tadeusz, czyli ostatni zajazd na Litwie",
    "Na Zachodzie bez zmian",
    "Mistrz i Małgorzata",
    "Duma i uprzedzenie",
    "Wojna i pokój",
    "Lew, czarownica i stara szafa",
    "Sposób na Alcybiadesa",
    "Tomek w krainie kangurów",
    "O psie, który jeździł koleją",
    "Kajko i Kokosz",
  ],
  "Bajka": [
    "O rybaku i złotej rybce",
    "Dziewczynka z zapałkami",
    "Nowe szaty cesarza",
    "Wilk i siedem koźlątek",
    "Trzy małe świnki",
    "Stoliczku, nakryj się",
    "Kot w butach",
    "Jaś i Małgosia",
    "Muzykanci z Bremy",
    "Królewna Śnieżka i siedmiu krasnoludków",
    "Piękna i Bestia",
    "Księżniczka na ziarnku grochu",
    "Jaś i magiczna fasola",
    "Ali Baba i czterdziestu rozbójników",
    "Bolek i Lolek",
    "Tom i Jerry",
    "Przygody kota Filemona",
    "Wilk i zając",
  ],
  "Legenda": [
    "Smok Wawelski i szewczyk Skuba",
    "Wars i Sawa",
    "Lech, Czech i Rus",
    "Popiel zjedzony przez myszy",
    "Pan Twardowski na Księżycu",
    "O złotej kaczce",
    "Śpiący rycerze w Tatrach",
    "Hejnał z wieży Mariackiej",
    "Bazyliszek z Krzywego Koła",
    "Koziołki z poznańskiego ratusza",
  ],
  "Polska piosenka": [
    "Przez twe oczy zielone",
    "Ona tańczy dla mnie",
    "Bo wszyscy Polacy to jedna rodzina",
    "Kocham cię, kochanie moje",
    "Ale to już było",
    "Dziwny jest ten świat",
    "Jolka, Jolka, pamiętasz",
    "Sen o Warszawie",
    "Chcemy być sobą",
    "Szczęśliwej drogi, już czas",
    "Windą do nieba",
    "Nie płacz, Ewka",
    "Wszystko czego dziś chcę",
    "Kiedy byłem małym chłopcem",
  ],
  "Piosenka dla dzieci": [
    "Wlazł kotek na płotek",
    "Jadą, jadą misie",
    "Panie Janie, rano wstań",
    "Była sobie żabka mała",
    "My jesteśmy krasnoludki",
    "Kolorowe kredki w pudełeczku noszę",
    "Wszystkie dzieci nasze są",
    "Mydło lubi zabawę",
    "Jedzie pociąg z daleka",
    "Ogórek, ogórek, ogórek, zielony ma garniturek",
  ],
  "Kolęda": [
    "Wśród nocnej ciszy",
    "Bóg się rodzi",
    "Cicha noc, święta noc",
    "Lulajże, Jezuniu, moja perełko",
    "Przybieżeli do Betlejem",
    "Dzisiaj w Betlejem",
    "Gdy się Chrystus rodzi",
    "Pójdźmy wszyscy do stajenki",
    "W żłobie leży",
    "Z narodzenia Pana dzień dzisiaj wesoły",
    "Anioł pasterzom mówił",
    "Tryumfy Króla Niebieskiego",
  ],
  "Boże Narodzenie": [
    "Opłatek przy wigilijnym stole",
    "Karp pływa w wannie",
    "Pierwsza gwiazdka na niebie",
    "Barszcz czerwony z uszkami",
    "Pasterka o północy",
    "Choinka z bombkami",
    "Prezenty pod choinką",
    "Dwanaście potraw wigilijnych",
    "Sianko pod obrusem",
    "Dodatkowe nakrycie dla wędrowca",
    "Święty Mikołaj z reniferami",
    "Pierniki z lukrem",
  ],
  "Wielkanoc": [
    "Śmigus-dyngus w lany poniedziałek",
    "Święcenie pokarmów w sobotę",
    "Koszyczek ze święconką",
    "Pisanki i kraszanki",
    "Żurek z białą kiełbasą",
    "Szukanie jajek w ogrodzie",
    "Baranek z cukru",
    "Mazurek z kajmakiem",
    "Palemka na Niedzielę Palmową",
    "Rzeżucha na parapecie",
    "Babka drożdżowa z lukrem",
  ],
  "Na weselu": [
    "Pierwszy taniec młodej pary",
    "Zabawy na oczepinach",
    "Goście krzyczą gorzko, gorzko",
    "Tort weselny z figurkami",
    "Panna młoda rzuca bukiet",
    "Powitanie chlebem i solą",
    "Poprawiny w niedzielę",
    "Welon panny młodej",
    "Wujek tańczy kaczuchy",
  ],
  "Na urodzinach": [
    "Tort ze świeczkami",
    "Sto lat, sto lat, niech żyje, żyje nam",
    "Pomyśl życzenie i zdmuchnij świeczki",
    "Prezent z kokardą",
    "Balony i konfetti",
    "Wszystkiego najlepszego z okazji urodzin",
    "Przyjęcie niespodzianka dla solenizanta",
  ],
  "Obiad": [
    "Kotlet schabowy z ziemniakami",
    "Pierogi ruskie ze skwarkami",
    "Bigos z kiełbasą",
    "Rosół z makaronem",
    "Żurek w chlebie",
    "Placki ziemniaczane ze śmietaną",
    "Gołąbki w sosie pomidorowym",
    "Naleśniki z serem",
    "Pomidorowa z ryżem",
    "Fasolka po bretońsku",
    "Ryba po grecku",
    "Jajecznica na boczku",
    "Frytki z keczupem",
    "Pizza z ananasem",
    "Kebab na cienkim cieście",
    "Zapiekanka z pieczarkami",
    "Mielony z mizerią",
  ],
  "Deser": [
    "Sernik na zimno",
    "Szarlotka z lodami",
    "Pączek z różą",
    "Gofry z bitą śmietaną",
    "Makowiec z bakaliami",
    "Karpatka z kremem",
    "Tort czekoladowy z wiśniami",
    "Galaretka z owocami",
    "Budyń waniliowy z sokiem",
    "Ciasto drożdżowe z kruszonką",
  ],
  "Napoje": [
    "Kawa z mlekiem",
    "Herbata z cytryną",
    "Kompot z suszu",
    "Lemoniada z miętą",
    "Grzane wino z goździkami",
    "Kakao z pianką",
    "Koktajl z truskawek",
    "Kawa po turecku",
    "Mleko z miodem",
    "Piwo z sokiem malinowym",
  ],
  "W kuchni": [
    "Deska do krojenia",
    "Tarka do sera",
    "Wałek do ciasta",
    "Ekspres do kawy",
    "Otwieracz do puszek",
    "Garnek z pokrywką",
    "Zmywarka do naczyń",
    "Podgrzewanie w mikrofalówce",
    "Czajnik z gwizdkiem",
    "Sól i pieprz",
    "Zeszyt z przepisami babci",
  ],
  "W domu": [
    "Pilot do telewizora",
    "Szczoteczka do zębów",
    "Suszarka do włosów",
    "Deska do prasowania",
    "Budzik na szafce nocnej",
    "Klucze do mieszkania",
    "Wieszak na ubrania",
    "Kosz na śmieci",
    "Doniczka z kwiatkiem",
    "Skarpetki zgubione w pralce",
    "Ładowarka do telefonu",
  ],
  "W szkole": [
    "Dzwonek na przerwę",
    "Kartkówka z matematyki",
    "Świadectwo z czerwonym paskiem",
    "Ściąga w piórniku",
    "Zeszyt w kratkę",
    "Wycieczka klasowa do Krakowa",
    "Pies zjadł zadanie domowe",
    "Tablica i kreda",
    "Wywiadówka u wychowawczyni",
    "Dyżur na korytarzu",
    "Apel na sali gimnastycznej",
    "Tabliczka mnożenia do stu",
  ],
  "Na zakupach": [
    "Kolejka do kasy",
    "Wózek na zakupy",
    "Promocja dwa w cenie jednego",
    "Płacę kartą zbliżeniowo",
    "Nieoczekiwany przedmiot w strefie pakowania",
    "Wielka wyprzedaż sezonowa",
    "Kolejka do przymierzalni",
    "Zwrot towaru z paragonem",
    "Lista zakupów na lodówce",
    "Szaleństwo czarnego piątku",
  ],
  "Nad morzem": [
    "Parawan na plaży",
    "Zamek z piasku",
    "Krem z filtrem",
    "Zimna woda w Bałtyku",
    "Ratownik na wieży",
    "Leżak pod parasolem",
    "Muszelki na piasku",
    "Rejs statkiem po zatoce",
    "Molo w Sopocie",
    "Ryba z frytkami",
    "Mewa kradnie frytki",
    "Zachód słońca nad morzem",
  ],
  "W górach": [
    "Morskie Oko w Tatrach",
    "Kolejka na Kasprowy Wierch",
    "Oscypek z żurawiną",
    "Nocleg w schronisku",
    "Szlak na Giewont",
    "Krupówki w Zakopanem",
    "Góral w kapeluszu",
    "Zejście po łańcuchach",
    "Wschód słońca na szczycie",
    "Plecak z prowiantem",
  ],
  "Zimą": [
    "Lepienie bałwana z marchewką",
    "Bitwa na śnieżki",
    "Kulig z pochodniami",
    "Jazda na łyżwach",
    "Ferie zimowe w górach",
    "Zjazd na sankach z górki",
    "Gorąca czekolada z piankami",
    "Czapka z pomponem",
    "Odśnieżanie samochodu rano",
    "Sople lodu na dachu",
  ],
  "Sport": [
    "Skok o tyczce",
    "Bieg przez płotki",
    "Czerwona kartka dla bramkarza",
    "Rzut karny w ostatniej minucie",
    "Złoty medal olimpijski",
    "Puchar Świata w skokach narciarskich",
    "Gol w doliczonym czasie",
    "Sędzia gwiżdże koniec meczu",
    "Kibice śpiewają na trybunach",
    "Tour de Pologne",
    "Rzuty karne po dogrywce",
  ],
  "Kosmos": [
    "Planety Układu Słonecznego",
    "Galaktyka Drogi Mlecznej",
    "Gwiazdozbiór Wielkiej Niedźwiedzicy",
    "Całkowite zaćmienie Słońca",
    "Lądowanie na Księżycu",
    "Mały krok dla człowieka",
    "Deszcz spadających gwiazd",
    "Łazik na Marsie",
    "Pierścienie wokół Saturna",
    "Kosmonauta w skafandrze",
    "Wstrzymał Słońce, ruszył Ziemię",
  ],
  "Zwierzęta": [
    "Kangur z młodym w torbie",
    "Pingwin na krze lodowej",
    "Wielbłąd z dwoma garbami",
    "Żyrafa z długą szyją",
    "Słoń z długą trąbą",
    "Kot mruczy na kolanach",
    "Pies merda ogonem",
    "Bocian w gnieździe",
    "Wiewiórka zbiera orzechy",
    "Jeż zwinięty w kulkę",
    "Niedźwiedź zapada w sen zimowy",
    "Kameleon zmienia kolor",
    "Papuga powtarza słowa",
    "Kura znosi jajka",
  ],
  "Znana postać": [
    "Król Bolesław Chrobry",
    "Król Kazimierz Wielki",
    "Królowa Bona Sforza",
    "Królowa Jadwiga Andegaweńska",
    "Król Władysław Jagiełło",
    "Naczelnik Tadeusz Kościuszko",
    "Marszałek Józef Piłsudski",
    "Cesarz Napoleon Bonaparte",
    "Kompozytor Fryderyk Chopin",
    "Wieszcz Adam Mickiewicz",
    "Astronom Mikołaj Kopernik",
    "Żeglarz Krzysztof Kolumb",
    "Kleopatra, królowa Egiptu",
    "Fizyk Albert Einstein",
  ],
  "Znane miejsce": [
    "Wieża Eiffla w Paryżu",
    "Krzywa wieża w Pizie",
    "Wielki Mur Chiński",
    "Statua Wolności w Nowym Jorku",
    "Pałac Kultury i Nauki",
    "Zamek Królewski na Wawelu",
    "Kopalnia soli w Wieliczce",
    "Rynek Główny w Krakowie",
    "Piramidy w Gizie",
    "Koloseum w Rzymie",
    "Big Ben w Londynie",
    "Zamek krzyżacki w Malborku",
    "Krasnale we Wrocławiu",
    "Brama Brandenburska w Berlinie",
  ],
  "Gry i zabawy": [
    "Raz, dwa, trzy, Baba Jaga patrzy",
    "Stary niedźwiedź mocno śpi",
    "Mam chusteczkę haftowaną",
    "Kółko i krzyżyk",
    "Gra w statki",
    "Zabawa w głuchy telefon",
    "Gra w klasy",
    "Zabawa w chowanego",
    "Zabawa w ciuciubabkę",
    "Gra w chińczyka",
    "Skakanie na skakance",
    "Podchody w lesie",
  ],
  "Hobby": [
    "Wędkowanie nad jeziorem",
    "Zbieranie znaczków pocztowych",
    "Układanie puzzli na stole",
    "Jazda na rowerze",
    "Zbieranie grzybów w lesie",
    "Uprawa pomidorów na działce",
    "Gra w planszówki",
    "Robienie na drutach",
    "Śpiewanie w karaoke",
    "Oglądanie seriali do rana",
    "Pieczenie chleba w domu",
    "Gra na gitarze",
  ],
};

export const PASSWORDS: Password[] = Object.entries(BANK).flatMap(([category, answers]) =>
  answers.map((answer) => ({ category, answer: answer.toLocaleUpperCase("pl") })),
);

/** Losuje hasło, którego nie było jeszcze w tej grze. */
export function pickPassword(used: Set<string>, rng: () => number = Math.random): Password {
  const fresh = PASSWORDS.filter((p) => !used.has(p.answer));
  const pool = fresh.length > 0 ? fresh : PASSWORDS;
  return pool[Math.floor(rng() * pool.length)];
}
